### PR TITLE
Merge dev to master

### PR DESCRIPTION
**Pull request by pasha**
- fixed specs

### CODE REVIEW

**Comment by dillo** [comment]
👍

**Comment by bmillares** [comment]
Hi guys,

I'm still getting github notifications but I have not worked at rent now
for over four years.

Can someone remove me from the notifications list?

Thanks,

Benny Millares

**Comment by martinstreicher** [comment]
You should be able to turn off notifications on the repo… but we should probably remove you from the team writ large.

**Comment by bmillares** [comment]
Yes, you guys probably should remove me.  I don't mind getting the emails,
they just get filed away, but there must be some liability issues if I
continue getting this stuff.  I'm sure the compliance officer(s) won't be
happy :)

Thanks,

bm

**Comment by pasha** [comment]
Hey @bmillares you are not part of the team, i double check. Since this is a public repo, you just need to unsubscribe.

**Pull request merged**
